[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["src"]
skip = ["venv", ".venv", "build", "dist"]
combine_as_imports = true

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["venv", ".venv", "build", "dist"]
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP"]
ignore = ["E203"]

